### ISSUE TITLE
404 link "Slides" in reusable materials

### ISSUE THREAD

**Issue by DanielaGawehns** [reprohack/reprohack-template-shiny#4]
Hey, there is a 404 behind the readme.md link to the slide deck. 

From the readme.md:
https://github.com/reprohack/reprohack-template-shiny -->

https://hackmd.io/link-to-copy-of-intro-slides/view

**Comment by annakrystalli** [comment]
That's because  the `link-to-copy-of-intro-slides/` part of the URL needs to be completed by the user. The template that can be imported to hack.md is  here: https://github.com/reprohack/reprohack-template-shiny/blob/master/slides.md

**Comment by DanielaGawehns** [comment]
*insert face-palm-emoji here*
Didn't get that I was looking at a template... Need more coffee. And lunch. Thanks for the quick help @annakrystalli
